create table public.conversion_events (
  id bigint generated by default as identity primary key,
  name text not null,
  path text,
  tour_slug text,
  collection text,
  destination text,
  pax integer,
  value_idr integer,
  created_at timestamptz not null default now(),
  constraint conversion_events_name_check check (name in (
    'tour_search',
    'collection_selected',
    'tour_viewed',
    'date_selected',
    'checkout_started',
    'booking_request_submitted',
    'whatsapp_clicked'
  )),
  constraint conversion_events_path_length_check check (path is null or char_length(path) <= 240),
  constraint conversion_events_tour_slug_length_check check (tour_slug is null or char_length(tour_slug) <= 120),
  constraint conversion_events_collection_length_check check (collection is null or char_length(collection) <= 80),
  constraint conversion_events_destination_length_check check (destination is null or char_length(destination) <= 80),
  constraint conversion_events_pax_check check (pax is null or pax between 1 and 30),
  constraint conversion_events_value_idr_check check (value_idr is null or value_idr between 0 and 1000000000)
);

create index conversion_events_name_created_at_idx on public.conversion_events (name, created_at);
create index conversion_events_created_at_idx on public.conversion_events (created_at);

alter table public.conversion_events enable row level security;
revoke all on table public.conversion_events from anon, authenticated;
revoke all on sequence public.conversion_events_id_seq from anon, authenticated;
