ALTER TYPE "BookingStatus" ADD VALUE 'REQUESTED' BEFORE 'PENDING';
ALTER TYPE "BookingStatus" ADD VALUE 'CONFIRMED' AFTER 'PAID';

ALTER TYPE "PaymentProviderName" ADD VALUE 'MANUAL' BEFORE 'MIDTRANS';
ALTER TYPE "PaymentStatus" ADD VALUE 'NOT_REQUIRED' BEFORE 'PENDING';
